project_id = "uizdqqyiqxkcjufkksrc"

[functions.eps-payment]
verify_jwt = false

[functions.stripe-payment]
verify_jwt = false

[functions.paypal-payment]
verify_jwt = false

[functions.sync-google-reviews]
verify_jwt = false
[functions.get-maps-key]
verify_jwt = false

[functions.google-sheets-sync]
verify_jwt = false

[functions.ai-generate-product]
verify_jwt = false

[functions.ai-smart-search]
verify_jwt = false

[functions.ai-bouquet-preview]
verify_jwt = false

[functions.notify-affiliate]
verify_jwt = false
